"""migracao inicial

Revision ID: a6ba59887af6
Revises: 
Create Date: 2026-07-24 12:57:37.236020

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6ba59887af6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brasil_db',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uf_id', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(), nullable=True),
    sa.Column('ano', sa.Integer(), nullable=True),
    sa.Column('populacao', sa.Integer(), nullable=True),
    sa.Column('sigla', sa.String(), nullable=True),
    sa.Column('regiao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_brasil_db_id'), 'brasil_db', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_brasil_db_id'), table_name='brasil_db')
    op.drop_table('brasil_db')
    # ### end Alembic commands ###
